=== SATALIN/LibraryIndex/src/main/webapp/WEB-INF/classes/SimpleLibraryIndex.xsd
<?xml version="1.0"?>
<!DOCTYPE LibraryIndex SYSTEM "LibraryIndex.dtd">
<xs:schema id="LibraryIndex"  xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="LibraryIndex" >
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="RedirectLinks">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Link" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="key" type="xs:string"  />
                    <xs:element name="value" type="xs:string"  />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="FileLibraryPath">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Path" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="target" type="xs:string"  />
                    <xs:element name="location" type="xs:string"  />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SATALIN/LibraryIndex/src/main/resources/ApplicationConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<LibraryIndex   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 				xsi:noNamespaceSchemaLocation="SimpleLibraryIndex.xsd" >
<RedirectLinks>
	<Link>
		<key>LIST</key>
		<value>/pages/libraryDo/listLibrary.jsp</value>
	</Link>
	<Link>
		<key>FIND</key>
		<value>/pages/libraryDo/findBook.jsp</value>
	</Link>
	<Link>
		<key>RETURN</key>
		<value>/pages/libraryDo/findBook.jsp</value>
	</Link>
	<Link>
		<key>ORDER</key>
		<value>/pages/libraryDo/findBook.jsp</value>
	</Link>
	<Link>
		<key>CREATEUSER</key>
		<value>/pages/userDo/createUser.jsp</value>
	</Link>
	<Link>
		<key>EDITUSER</key>
		<value>/pages/userDo/editUser.jsp</value>
	</Link>
		<Link>
		<key>GETUSER</key>
		<value>/pages/userDo/editUser.jsp</value>
	</Link>
		<Link>
		<key>DELETEUSER</key>
		<value>/pages/userDo/listUser.jsp</value>
	</Link>
		<Link>
		<key>LISTUSER</key>
		<value>/pages/userDo/listUser.jsp</value>
	</Link>
			<Link>
		<key>LIST_LIBRARIES</key>
		<value>/pages/libraryDo/listLibrary.jsp</value>
	</Link>
			<Link>
		<key>ERROR</key>
		<value>/pages/error.jsp</value>
	</Link>
			<Link>
		<key>LOGIN</key>
		<value>/index.jsp</value>
	</Link>
</RedirectLinks>
<FileLibraryPath>
	<Path>
		<target>ALL</target>
		<location>D:/SATALIN/temp/index/</location>
	</Path>
</FileLibraryPath>
</LibraryIndex>
